version: '3.8'

services:
  mcp-neo4j-remote:
    build: .
    container_name: mcp-neo4j-remote
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - NEO4J_URI=${NEO4J_URI:-bolt://macmini.arturs-server.com:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-nohuprsz}
      - NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}
      - DESCOPE_PROJECT_ID=${DESCOPE_PROJECT_ID}
      - DESCOPE_MANAGEMENT_KEY=${DESCOPE_MANAGEMENT_KEY}
      - API_KEYS=${API_KEYS}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Local Neo4j for development
  neo4j-dev:
    image: neo4j:5.15
    container_name: neo4j-dev
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    profiles:
      - dev

volumes:
  neo4j_data:
  neo4j_logs: